---
baseurl: http://www.forestry.io/docs
languagecode: en-us
pluralizelisttitles: false
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
theme: forestry-doc-theme
title: The Forestry Field Guide
menu:
  main:
  - Name: Getting Started
    URL: "/Getting-Started/"
    Weight: -100
    weight: 1
  - Name: GitHub & Forestry
    URL: "/GitHub-and-forestry-io/"
    Weight: -90
    weight: 2
