---
baseurl: http://www.forestry.io/docs
languagecode: en-us
menu:
  main:
    - Name: "Getting Started"
      Weight: -100
      URL: "/Getting-Started/"
    - Name: "GitHub & Forestry"
      Weight: -90
      URL: "/GitHub-and-forestry-io/"
pluralizelisttitles: false
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
theme: forestry-doc-theme
title: The Forestry Field Guide
