---
title: The Forestry Field Guide
theme: forestry-doc-theme
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
pluralizelisttitles: false
permalinks:
  doc: "/:title/"
languagecode: en-us
baseurl: https://forestry.io/docs
menu:
  main:
  - name: Getting Started
    url: "/Getting-Started/"
    weight: 1
