---
baseurl: https://forestry.io/docs
languagecode: en-us
permalinks:
  doc: "/:title/"
pluralizelisttitles: false
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
theme: forestry-doc-theme
title: The Forestry Field Guide
menu:
  getting-started:
  - name: Getting Started
    url: "/Getting-Started/"
    weight: 1
  setting-up-site:
  - name: Getting Started
    url: "/Getting-Started/"
    weight: 1
  deployment-and-hosting:
    - name: Getting Started
      url: "/Getting-Started/"
      weight: 1
