---
baseurl: https://forestry.io/docs
languagecode: en-us
permalinks:
  doc: "/:title/"
pluralizelisttitles: false
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
theme: forestry-doc-theme
title: The Forestry Field Guide
