---
baseurl: https://forestry.io/docs
languagecode: en-us
permalinks:
  doc: "/:title/"
pluralizelisttitles: false
sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: "-1"
theme: forestry-doc-theme
title: The Forestry Field Guide
menu:
  setting_up_a_site:
  - name: Importing a site from Github
    weight: 2
