theme:  "forestry-doc-theme"
baseurl: "docs.forestry.io"
languageCode: "en-us"
title: "The Forestry Field Guide"
taxonomies:
  category:  "categories"
  tag:  "tags"
menu.main:
  name : "Sermons"
  url : "/sermon"
  weight : 1
menu.main:
  name : "Events"
  url : "/event"
  weight : 2